stages:
  preprocess:
    cmd: python src/preprocessPipeline.py
    deps:
    - src/preprocessFunctionCollection.py  
    - src/preprocessPipeline.py
    - data/MovieDataset.csv
    outs:
    - data/processedData.csv
  traintestModel:
    cmd: python src/trainTestModelPipeline.py
    deps:
    - src/preprocessPipeline.py
    - data/processedData.csv
    metrics:
    - metrics.json:
        cache: false