version: '3.8'

services:
  model_env:
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    env_file:
      - .env
    volumes:
    - type: bind
      source: ./data
      target: /model/data
      read_only: true
    - type: bind
      source: ./trained_model
      target: /model/trained_model
      read_only: true
    working_dir: /model
    command: tail -f /dev/null
